// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"fraud-scoring/internal/adapter/grpc/out"
	"fraud-scoring/internal/adapter/kafka/in"
	out2 "fraud-scoring/internal/adapter/kafka/out"
	"fraud-scoring/internal/domain/application"
	"fraud-scoring/internal/infra/grpc"
	"fraud-scoring/internal/infra/kafka"
	"fraud-scoring/internal/infra/logger"
)

// Injectors from wire.go:

func buildAppContainer() (*Manager, error) {
	userTransactionsConfig := api.NewUserTransactionsConfig()
	userTransactionsServiceClient := api.NewUserTransactionGrpc(userTransactionsConfig)
	grpcUserTransactionsRepository := out.NewGrpcUserTransactionsRepository(userTransactionsServiceClient)
	saramaConfig := kafka.NewSaramaConfig()
	cloudEventsSender, err := kafka.NewCloudEventsKafkaSender(saramaConfig)
	if err != nil {
		return nil, err
	}
	zapLogger := logger.NewLogger()
	kafkaTransactionScoreCard := out2.NewKafkaTransactionScoreCard(cloudEventsSender, zapLogger)
	paymentRiskScoring := application.NewPaymentRiskScoring(grpcUserTransactionsRepository, kafkaTransactionScoreCard, zapLogger)
	checkoutEventReceiver := in.NewCheckoutEventReceiver(paymentRiskScoring, zapLogger)
	cloudEventsReceiver, err := kafka.NewCloudEventsKafkaConsumer(saramaConfig)
	if err != nil {
		return nil, err
	}
	manager := NewManager(checkoutEventReceiver, cloudEventsReceiver)
	return manager, nil
}
